apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    name: memcached
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
