kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "django-app-build" 
spec:
  runPolicy: "Serial" 
  source: 
    git:
      uri: "https://some-repository-url/"
  strategy: 
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "python-27-centos7:latest"
  output: 
    to:
      kind: "ImageStreamTag"
      name: "django-app:latest"
